pirelimap1/Models/Tire.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace pirelimap1.Models
{
    public class Tire
    {
        public int ID { get; set; }
        [Required]
        public string NameTire { get; set; }
        public string Adress { get; set; }
        public int Zipcode { get; set; }
        
    }
}

pirelimap1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace pirelimap1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

pirelimap1/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using pirelimap1.Data;

namespace pirelimap1.Controllers
{


    //[Produces("application/json")]
    
    public class MapController : Controller
    {
        private readonly TireContext _context;

        public MapController(TireContext context)
        {
            _context = context;
        }

        [Route("api/Map")]
        [HttpGet]
        public IActionResult Index()
        {
            
            return View();
        }

        [Route("api/Map/MapAddresses")]
        [HttpGet]
        public IActionResult MapAddresses()
        {
            var lst = _context.Tires.Select(x => x.Adress).ToList();
            return Json(lst);
        }
        [Route("api/Map/MapTiresNames")]
        [HttpGet]
        public IActionResult MapTiresNames()
        {
            var TireName = _context.Tires.Select(x => x.NameTire).ToList();
            return Json(TireName);
        }


    }
}

pirelimap1/Controllers/TiresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pirelimap1.Data;
using pirelimap1.Models;

namespace pirelimap1.Controllers
{
    public class TiresController : Controller
    {
        private readonly TireContext _context;

        public TiresController(TireContext context)
        {
            _context = context;    
        }

        // GET: Tires
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;
            var tires = from s in _context.Tires
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                tires = tires.Where(s => s.NameTire.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    tires = tires.OrderBy(s => s.NameTire);
                    break;
                case "Date":
                    tires = tires.OrderBy(s => s.Adress);
                    break;
                case "date_desc":
                    tires = tires.OrderByDescending(s => s.Zipcode);
                    break;
               
            }
            return View(await tires.AsNoTracking().ToListAsync());
        }

        // GET: Tires/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tire = await _context.Tires
                .SingleOrDefaultAsync(m => m.ID == id);
            if (tire == null)
            {
                return NotFound();
            }

            return View(tire);
        }

        // GET: Tires/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tires/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,NameTire,Adress,Zipcode")] Tire tire)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(tire);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
        
            return View(tire);
        }

        // GET: Tires/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tire = await _context.Tires.SingleOrDefaultAsync(m => m.ID == id);
            if (tire == null)
            {
                return NotFound();
            }
            return View(tire);
        }

        // POST: Tires/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,NameTire,Adress,Zipcode")] Tire tire)
        {
            if (id != tire.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tire);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TireExists(tire.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(tire);
        }

        // GET: Tires/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tire = await _context.Tires
                 .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (tire == null)
            {
                return NotFound();
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(tire);
        }

        // POST: Tires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tire = await _context.Tires.SingleOrDefaultAsync(m => m.ID == id);
            _context.Tires.Remove(tire);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool TireExists(int id)
        {
            return _context.Tires.Any(e => e.ID == id);
        }
    }
}

pirelimap1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

pirelimap1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

pirelimap1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/Couresel1.jpg" alt="ASP.NET" class="center-block" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/carousel2.jpg" alt="Visual Studio" class="center-block" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

pirelimap1/Views/Map/Index.cshtml
@*@{
        ViewData["Title"] = "Index";
    }*@
<html>
<head>
    <title>Map</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">

    @*<h2>Map</h2>*@

    ﻿
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyBVNGw7EdYnMUbaWMb6eakS66tFIrjqEfY" type="text/javascript"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    </head>
<body>

        <style>
            #map_canvas img {
                max-width: none;
            }
        </style>

        <!-- This css is to give a nice big popup "info window" when a marker is clicked on the map -->
        <style>
            .infoDiv {
                height: 200px;
                width: 300px;
                -webkit-user-select: none;
                background-color: white;
            }
        </style>

        <br />
        <!-- This is the div that will contain the Google Map -->
        <div id="map_canvas" style="height: 550px;"></div>
    
  
    <!-- Enclose the Javascript in a "section" so that it is rendered in the correct order after scripts have been loaded etc -->
        @section scripts {
            <section class="scripts">

                <script type="text/javascript">

   // <!-- This code tells the browser to execute the "Initialize" method only when the complete document model has been loaded. -->
    $(document).ready(function () {
        Initialize();
    });


    // Where all the fun happens
    function Initialize() {
        var addresses = [];
          @*addresses = @ViewBag.AddressLst;*@
            $.get("Map/MapAddresses", function (data) {
                $(".result").html(data);
                    addresses = data;
                    console.log(addresses)
                    //geocodeAddresses(addresses);
                    });

                    $.get("Map/MapTiresNames", function (data) {
                        $(".result").html(data);
                        Names = data;

                        geocodeAddresses(addresses, Names);
                    });




            // Google has tweaked their interface somewhat - this tells the api to use that new UI
              google.maps.visualRefresh = true;

        var Tunisie = new google.maps.LatLng(36.81881, 10.16596);

        // These are options that set initial zoom level, where the map is centered globally to start, and the type of map to show
        var mapOptions = {
            zoom: 8,
            center: Tunisie,
                    mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
                    };

                    var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);


                    function geocodeAddresses() {
                        for (var i = 0; i < addresses.length; i++) {
                            geocodeAddress(addresses[i],Names[i])
                        }
                    }

                    function geocodeAddress(addresses, Names) {
                        currNeme = Names
                        currAddress = addresses;

                        var infowindow = new google.maps.InfoWindow();
                        var geocoder = new google.maps.Geocoder();

                        if (geocoder) {
                            console.log(currAddress);
                            await geocoder.geocode({ 'address': currAddress }, function (results, status) {
                              
                                    if (status == google.maps.GeocoderStatus.OK) {
                                        console.log(currAddress);

                                        var marker = new google.maps.Marker({
                                            'position': results[0].geometry.location,
                                            'map': map,
                                            'title': currAddress

                                        });
                                        //console.log(currAddress);
                                        console.log(results[0].formatted_address);


                                        var infowindow = new google.maps.InfoWindow({
                                            content: "<div class='infoDiv'><h2>" + Names + "</div></div> " + results[0].formatted_address
                                        });

                                        google.maps.event.addListener(marker, 'click', function () {
                                            infowindow.open(map, marker);
                                        });

                                        //google.maps.event.addListener(marker, 'click', (function (marker, i) {
                                        //    return function () {
                                        //        infowindow.setContent("<div class='infoDiv'><h2>" + currAddress + "</div></div>");
                                        //        infowindow.open(map, marker);
                                        //    }
                                        //})(marker, i));



                                    }
                                    else {
                                        alert("Geocode was not successful for the following reason: " + status);
                                    }
                             

                                });
                            
                                
                            } 
               
            
                    }
                    

        // This makes the div with id "map_canvas" a google map
                    //var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);


        // a sample list of JSON encoded data of places to visit in Tunisia
        // you can either make up a JSON list server side, or call it from a controller using JSONResult
        //var data = [
        //          { "Id": 1, "PlaceName": "Zaghouan", "GeoLong": "36.401081", "GeoLat": "10.16596" },
        //          { "Id": 2, "PlaceName": "Hammamet ", "GeoLong": "36.4", "GeoLat": "10.616667" },
        //          { "Id": 3, "PlaceName": "Sousse", "GeoLong": "35.8329809", "GeoLat": "10.63875" },
        //          { "Id": 4, "PlaceName": "Sfax", "GeoLong": "34.745159", "GeoLat": "10.7613" }
        //       ];

        // Using the JQuery "each" selector to iterate through the JSON list and drop marker pins
        //$.each(data, function (i, item) {
        //    var marker = new google.maps.Marker({
        //        'position': new google.maps.LatLng(item.GeoLong, item.GeoLat),
        //        'map': map,
        //        'title': item.PlaceName
        //    });

            // Make the marker-pin blue!
        //    marker.setIcon('http://maps.google.com/mapfiles/ms/micons/mechanic.png')

        //    // put in some information about each json object - in this case, the opening hours.
        //    var infowindow = new google.maps.InfoWindow({
        //        content: "<div class='infoDiv'><h2>" + item.PlaceName + "</div></div>"
        //    });

        //    // finally hook up an "OnClick" listener to the map so it pops up out info-window when the marker-pin is clicked!
        //    google.maps.event.addListener(marker, 'click', function () {
        //        infowindow.open(map, marker);
        //    });

        //})
    }


                </script>
            </section>
        }
        </body>
</html>

pirelimap1/Views/Map/Map.cshtml
@{
    ViewData["Title"] = "Map";
}

<h2>Map</h2>

pirelimap1/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pirelimap1</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">pirelimap1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - pirelimap1</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

pirelimap1/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pireli</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span >
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"> 
                <img src="~/images/logo-pirelli.jpg" style="display:inline-block;width:80%;"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"  style="line-height:100px; height:60px;">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Tires" asp-action="Index">Tires</a></li>
                    <li><a asp-area="" asp-controller="Map" asp-action="Index">Map</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - pirelli</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

pirelimap1/Views/Tires/Create.cshtml
@model pirelimap1.Models.Tire

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Tire</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NameTire" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NameTire" class="form-control" />
                <span asp-validation-for="NameTire" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Adress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Zipcode" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

pirelimap1/Views/Tires/Delete.cshtml
@model pirelimap1.Models.Tire

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tire</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.NameTire)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NameTire)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>